export const ADD_PRODUCTS_INFO = "ADD_PRODUCTS_INFO";
export const LOGIN_USER = "LOGIN_USER";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
