import type { Metadata } from 'next'
import { Providers } from '@/redux/providers'
import { SessionAuthProvider } from '@/redux/context/SessionProvaider'
import { Inter } from 'next/font/google'
import '@/Style/globals.css'
import * as Components from "@/Components";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/impresora-3d.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>PrintCraft3D</title>
      </head>
      <body className={inter.className}>
        <Providers>
          <main className='bg-sky-100'>
            <SessionAuthProvider>
              <Components.Navbar />
              {children}
            </SessionAuthProvider>
            <Components.Footer />
          </main>
        </Providers>

      </body>

    </html>
  )
}
