import type { Metadata } from 'next'
import { Providers } from '@/redux/providers'
import { Inter } from 'next/font/google'
import '@/Style/globals.css'
import * as Components from "@/Components";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">

      <body className={inter.className}>
        <Providers>
          <main className='bg-sky-100'>
            <Components.Navbar />
            {children}
            <Components.Footer />
          </main>
        </Providers>

      </body>

    </html>
  )
}
